#lang racket
(require quickcheck)
(require shrubbery)
(require shrubbery/parse)
(require shrubbery/property)
(require shrubbery/write)
(require shrubbery/print)

(provide pretty_print_random_generated_vals
         raw_pretty_print_random_generated_vals)

(define cur-output-port (current-output-port))

;;; Self-defined pretty_printer for sexp in parsed representation list to default string
(define (pretty_print_sexp s [port cur-output-port])
  ;;; Attempt to write shrubbery to string first
  (define test-port (open-output-string))
  (write-shrubbery s test-port #:pretty? #t #:armor? #f #:prefer-multiline? #t)

  (define out-str (get-output-string test-port))
  (define in-port (open-input-string out-str))

  (with-handlers ([exn:fail? (lambda (e)
                               (displayln (format "Parse failed: ~a" (exn-message e)))
                               #f)])
    (when (parse-all in-port)
      ;; Only write to predefined port if the default parser succeeds
      (write-shrubbery s port #:pretty? #t #:armor? #f #:prefer-multiline? #t)
      (newline)
      (newline))))

(define (pretty_print_sexp_raw s [port cur-output-port])
  (write-shrubbery s port #:pretty? #t #:armor? #f #:prefer-multiline? #t)
  (newline)
  (newline))

;;; Self-defined pretty printer that will pretty prints the datum generated by random generator.
(define (pretty_print_random_generated_vals gen-generator [n 25] [port cur-output-port])
  (with-test-count n (quickcheck (property ([ele (gen-generator)]) (pretty_print_sexp ele port) #t))))

(define (raw_pretty_print_random_generated_vals gen-generator [n 25] [port cur-output-port])
  (with-test-count
      n
    (quickcheck (property ([ele (gen-generator)]) (pretty_print_sexp_raw ele port) #t))))
